# Generated by Django 5.0.6 on 2024-06-30 17:32

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='audio_file',
            field=models.FileField(upload_to=app.models.upload_file),
        ),
    ]
