# Generated by Django 5.0.6 on 2024-06-30 19:24

import app.models
import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_audioclip_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclip',
            name='audio_file',
            field=models.FileField(upload_to=app.models.upload_file, validators=[app.validators.validate_file_extension]),
        ),
    ]
